# Generated by Django 6.1.1 on 2026-09-04 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('risk_zones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High'), ('Severe', 'Severe')], max_length=20)),
                ('message', models.TextField()),
                ('language', models.CharField(default='en', max_length=10)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('push', 'Push'), ('both', 'SMS + Push')], default='sms', max_length=20)),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('explanation', models.TextField(blank=True, default='')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='risk_zones.riskzone')),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-dispatched_at'],
            },
        ),
    ]
