# Generated by Django 6.1.1 on 2026-09-04 18:52

import apps.risk_zones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLandslide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(blank=True, null=True)),
                ('geom', apps.risk_zones.models._PointField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, default='', max_length=20)),
                ('source', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'db_table': 'historical_landslides',
            },
        ),
        migrations.CreateModel(
            name='RiskZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(blank=True, default='', max_length=255)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('geom', apps.risk_zones.models._PolygonField(blank=True, null=True)),
                ('current_risk_level', models.CharField(default='Low', max_length=20)),
                ('last_computed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'risk_zones',
            },
        ),
    ]
