# Generated by Django 6.1.1 on 2026-09-04 18:52

import apps.reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', apps.reports.models._PointField(blank=True, null=True)),
                ('photo_url', models.TextField(blank=True, default='')),
                ('video_url', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('report_type', models.CharField(choices=[('landslide', 'Landslide'), ('flood', 'Flood'), ('road_block', 'Road Block'), ('crack', 'Crack/Subsidence'), ('other', 'Other')], default='other', max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('sync_status', models.CharField(choices=[('synced', 'Synced'), ('pending', 'Pending'), ('conflict', 'Conflict')], default='synced', max_length=20)),
            ],
            options={
                'db_table': 'field_reports',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
