# Generated by Django 6.1.1 on 2026-09-04 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('risk_zones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=50)),
                ('reading_time', models.DateTimeField()),
                ('rainfall_mm', models.FloatField(blank=True, null=True)),
                ('soil_moisture_pct', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=50)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_readings', to='risk_zones.riskzone')),
            ],
            options={
                'db_table': 'weather_readings',
                'ordering': ['-reading_time'],
            },
        ),
    ]
